export const colors = [
  {
    color: 'red',
    code: '#FF4747',
    music: '/music/red.mp3',
    isPicked: false,
    image: '/images/red.jpg',
  },
  {
    color: 'green',
    code: '#5EE06B',
    music: '/music/green.mp3',
    isPicked: false,
    image: '/images/green.jpg',
  },
  {
    color: 'blue',
    code: '#4857E0',
    music: '/music/blue.mp3',
    isPicked: false,
    image: '/images/blue.jpg',
  },
  {
    color: 'black',
    code: '#181818',
    music: '/music/black.mp3',
    isPicked: false,
    image: '/images/black.jpg',
  },
  {
    color: 'pink',
    code: '#FF6BD3',
    music: '/music/pink.mp3',
    isPicked: false,
    image: '/images/pink.jpg',
  },
  {
    color: 'yellow',
    code: '#FFFC52',
    music: '/music/yellow.mp3',
    isPicked: false,
    image: '/images/eraser.jpg',
  },
  {
    color: 'cyan',
    code: '#73F7FF',
    music: '/music/cyan.mp3',
    isPicked: false,
    image: '/images/eraser.jpg',
  },
  {
    color: 'eraser',
    code: 'white',
    music: '/music/white.mp3',
    isPicked: false,
    image: '/images/eraser.jpg',
  },
]
